name: Build Jupyter Notebook Container
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date to tag the image with
      run: echo "TODAY=$(TZ='America/Denver' date +'%Y.%m.%d')" >> $GITHUB_ENV
    - name: Checkout files in repo
      uses: actions/checkout@main
    - name: Build pudl-jupyter docker image with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        IMAGE_NAME: "catalystcoop/pudl-jupyter"
        ADDITIONAL_TAG: ${{ env.TODAY }}
        NOTEBOOK_USER: jovyan
        PUBLIC_REGISTRY_CHECK: true
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
